### ISSUE TITLE
ESLint Error when using ref 

### ISSUE THREAD

**Issue by skube** [alexgarces/react-typeform-embed#11]
In your [example popup](https://github.com/alexgarces/react-typeform-embed/blob/master/src/examples/ExamplePopup.js) you show:
`ref={(tf => this.typeformEmbed = tf) }/>`

My ESLint gives an error:
`[eslint] Arrow function should not return assignment. (no-return-assign)`

**Comment by alexgarces** [comment]
@skube thanks! I'll take a look ASAP.

**Comment by alexgarces** [comment]
@skube fixed in **v.0.2.0** :)
