### ISSUE TITLE
Gatsby build causes "WebpackError: window is not defined" error

### ISSUE THREAD

**Issue by skube** [alexgarces/react-typeform-embed#12]
When using Gatsby (v 1.1.45), I can `gatsby develop` just fine and see embedded Typeforms.

However, when using `gatsby build` I get a webpack error: **window is not defined**

**Comment by skube** [comment]
Seems to work now...so I dunno.

**Comment by alexgarces** [comment]
@skube thanks for the info!

**Comment by DomVinyard** [comment]
also getting this, it's an SSR issue right?
