### ISSUE TITLE
popup=true breaks button onClick with default create-react-app

### ISSUE THREAD

**Issue by 0xdevalias** [alexgarces/react-typeform-embed#13]
I'm not 100% on what the issue here is, or why, but just tried this library out and when I set `popup={true}`, any buttons in the same render block no longer seem able to run their `onClick`

```
"react": "^16.3.2",
"react-dom": "^16.3.2",
"react-typeform-embed": "^0.1.5",
```

```
render() {
    return (
      <div className="ExamplePopup">
        <ReactTypeformEmbed
          popup={true}
          url={'https://demo.typeform.com/to/njdbt5'} />

        <button onClick={()=> alert(1)}>Foo</button>
      </div>
    )
  }
```

When I comment out the `popup={true}` I can click the button and get an alert, when I add it back in, nothing fires. Debugging with the react dev tools, I can see that the onClick event is still bound to it, and when I "store as global" and call it from the console, it fires correctly. So.. not sure what's going on here.

**Edit:** Trying to replicate this in a clone of this repo, changing/adding libraries/etc, and so far can't break it.. Non-deterministic issues!

**Edit2:** Ok, seem to be able to replicate this as follows:

```
create-react-app break
cd break
npm i react-typeform-embed
```

Create a new file `ExamplePopup.js` with code copied from this repo:

```
import React from 'react';
import { ReactTypeformEmbed } from 'react-typeform-embed';

class ExamplePopup extends React.Component {
  constructor(props) {
    super(props);
    this.openForm = this.openForm.bind(this);
  }

  openForm() {
    this.typeformEmbed.typeform.open();
  }

  render() {
    return (
      <div className="ExamplePopup">
        <ReactTypeformEmbed
          popup={true}
          autoOpen={false}
          url={'https://demo.typeform.com/to/njdbt5'}
          hideHeaders={true}
          hideFooter={true}
          buttonText="Go!"
          style={{top: 100}}
          ref={(tf => this.typeformEmbed = tf) }/>

        <button className="btn" onClick={this.openForm} style={{cursor: 'pointer'}}>Click to open the popup!</button>
      </div>
    );
  }
}

export default ExamplePopup;
```

Edit `App.js` to include the following additional lines:

```
import ExamplePopup from './ExamplePopup';
```
And in the `render()`
```
<ExamplePopup/>
```

Then `npm start`.

The button shows, but when you attempt to click on it, nothing happens.

**Comment by alexgarces** [comment]
@0xdevalias thanks for reporting the issue, I'll take a look ASAP!

**Comment by alexgarces** [comment]
@0xdevalias I think it's a problem with the layout/styling. Just use `position: relative` in the parent component  to fix the issue:

`<div className="ExamplePopup" style={{ position: 'relative' }}>`

That should do the trick by now! ;)

If a future I will review the default styles of the component. Maybe using `position: absolute` on widget mode is not a good idea. Thanks for letting me know!
