### ISSUE TITLE
onSubmit not working

### ISSUE THREAD

**Issue by vgm8** [alexgarces/react-typeform-embed#14]
I have the PRO + account and I'm trying to print the result of the onSubmit callback but its undefined.

This is my code right now: 

```
class TypeForm extends React.Component {
  onSubmit(args) {
    console.log('onSubmit', args);
  }
  render() {
    return (
      <div className="type-form''>
        <ReactTypeformEmbed
          onSubmit={this.onSubmit}
          popup={false}
          url={this.props.url}/>
      </div>
    );
  }
};
```

Thanks in advance.

**Comment by scrofungulus** [comment]
At a quick glance, I'm guessing the problem you're having is from forgetting to `bind` your class method.

Updating your function to the following should fix your issue. 

```
render() {
    return (
      <div className="type-form''>
        <ReactTypeformEmbed
          onSubmit={this.onSubmit.bind(this)}
          popup={false}
          url={this.props.url}/>
      </div>
    );
  }
```

You can read more about handling events in React [here](https://reactjs.org/docs/handling-events.html).

**Comment by vgm8** [comment]
Thanks for the answer but I already tried that and I'm still not receiving the response object.

**Comment by scrofungulus** [comment]
Well could you provide the code for the entire file?

**Comment by vgm8** [comment]
My component it's a very basic wrapper:

```
import React from 'react';
import { ReactTypeformEmbed } from 'react-typeform-embed';
import './TypeForm.styl';

class TypeForm extends React.Component {
  onSubmit(arg) {
    console.log(arg)
  }
  render() {
    return (
      <div className={`type-form contract-form ${this.props.className || ''}`}>
        <ReactTypeformEmbed
          onSubmit={this.onSubmit.bind(this)}
          popup={false}
          url={this.props.url}/>
      </div>
    );
  }
};

export default TypeForm
```

**Comment by davesnx** [comment]
Hello @vgm8 and @alexgarces 

Here a Software Engineer working on the "Form experience" at Typeform. 

This library works fine with `onSubmit` prop. Currently, we don't send the answers on the submit callback. It's a business decision but we could be open to change it.

Could you fill out this [typeform](https://collect.typeform.com/to/F9jz78) to reflect your use case?

Thank you very much!

**Comment by bsiddiqui** [comment]
I'm not getting the onSubmit event either

**Comment by alexgarces** [comment]
@vgm8 @davesnx @scrofungulus sorry I couldn't attend this issue earlier.

As @davesnx reports, the official sdk is not providing the response to `onSubmit`.

Thank you all!

**Comment by evinracher** [comment]
Your documentation still said that you provide the response. So, does it?

https://developer.typeform.com/embed/onsubmit-callback/

**Comment by davesnx** [comment]
Hey @evinracher, left Typeform last year but the documentation mentions the response_id which matches with the responses API: https://developer.typeform.com/responses/reference/retrieve-responses

cc @epallerols

**Comment by evinracher** [comment]
> Hey @evinracher, left Typeform last year but the documentation mentions the response_id which matches with the responses API: https://developer.typeform.com/responses/reference/retrieve-responses
> 
> cc @epallerols

Thanks, I don't know what was happening but it works now.

**Comment by picsoung** [comment]
thank you @davesnx for jumping in 😉 

the `event.response_id` is a new feature that has been added couple of months ago. The `onSubmit` documentation you linked is correct.

**Comment by evinracher** [comment]
Thanks @picsoung

**Comment by taehyoungkim** [comment]
I'm trying to get the `event.response_id` by following the [popup example](https://github.com/alexgarces/react-typeform-embed/blob/master/src/examples/ExamplePopup.js), however all I'm getting is `undefined`. 

Here is my wrapper code, almost exactly following the example:

```javascript
import React from "react";
import { ReactTypeformEmbed } from "react-typeform-embed";
import { Button } from "antd";

class Survey extends React.Component {
  constructor(props) {
    super(props);
    this.openForm = this.openForm.bind(this);
    this.onSubmit = this.onSubmit.bind(this);
  }

  openForm() {
    this.typeformEmbed.typeform.open();
  }

  onSubmit(event) {
    console.log(event);
  }

  render() {
    return (
      <div>
        <ReactTypeformEmbed
          popup
          autoOpen={false}
          url="https://yeon-us.typeform.com/to/bKyjFtZ8"
          hideHeaders
          hideFooter
          buttonText="Go!"
          style={{ top: 100, position: "relative" }}
          ref={(tf) => {
            this.typeformEmbed = tf;
          }}
          onSubmit={this.onSubmit}
        />
        <Button
          className="btn"
          onClick={this.openForm}
          style={{ cursor: "pointer" }}
        >
          Click to open the popup!
        </Button>
      </div>
    );
  }
}

export default Survey;

```

`onSubmit` gets called but console.logs `undefined`
