### ISSUE TITLE
Please add an explicit license

### ISSUE THREAD

**Issue by phlipper** [alexgarces/react-typeform-embed#16]
Hello,

Thank you for providing this library! I would like to use this in a project but there is currently no explicit license granted to this work. Would you please consider releasing this under a license such as MIT?

Please see the following references for more details:

* [Licensing a repository](https://help.github.com/articles/licensing-a-repository/)
* [Why do people care so much about the legal side of open source?](https://opensource.guide/legal/#why-do-people-care-so-much-about-the-legal-side-of-open-source)

Thank you very much for the consideration.

**Comment by alexgarces** [comment]
#17 merge request added to **v.0.2.0** :)*
