### ISSUE TITLE
Weird refresh

### ISSUE THREAD

**Issue by PaulRBerg** [alexgarces/react-typeform-embed#2]
I've just tried this component on a simple page with a div and the Typeform as the single child. I cannot make it work without this annoying refresh: http://sendvid.com/chc8cy5p

I have tried removing the classes from the `div`. Is this related to some internal `<input>` tag?

```
<div className={'container-fluid-content pay'}>
    <ReactTypeformEmbed url={'LINK'}/>
</div>
```

**Comment by vitalyliber** [comment]
I have the same problem..

**Comment by vitalyliber** [comment]
@PaulRBerg I updated version '"typeform/embed": "^0.4.2",' in dependences. Issue took away =)

**Comment by alexgarces** [comment]
@PaulRBerg @vitalyliber I updated typeform/embed to the last current version (0.5.6).

It works properly now. Thanks! :)
