### ISSUE TITLE
How to handle hidden fields?

### ISSUE THREAD

**Issue by dimitry12** [alexgarces/react-typeform-embed#22]
Should I just add them to the `url` prop of the component?

**Comment by Gonzalo9823** [comment]
I did that and worked perfectly, like this

`url={`https://xxxxxxxxxxxx.typeform.com/to/jRxQ18user_id=${this.props.user.id}&user_name=${this.props.user.name}`}`

**Comment by ibrahimkante** [comment]
should be something like url={https://xxxxxxxxxxxx.typeform.com/to/jRxQ18?user_id=${this.props.user.id}&user_name=${this.props.user.name}`}`

I updated the url to add the "?' before user_id

**Comment by wisejayden** [comment]
It's weird how the official Hubspot docs state a # tag prefixing the hidden fields param... 

But I can confirm that @ibrahimkante is correct with using the "?"!
