### ISSUE TITLE
found 19 vulnerabilities (4 low, 11 moderate, 4 high)

### ISSUE THREAD

**Issue by Gonzalo9823** [alexgarces/react-typeform-embed#24]
Hey after installing this npm told me that it had many vulnerabilities, I'm going to try to fix them but just so you people know.

**Comment by daydream05** [comment]
I'm having the same issue. Would love to get an update on this

**Comment by daydream05** [comment]
All of the issues are from [react-scripts](https://www.npmjs.com/package/react-scripts) so I think updating to the latest version would solve this issue

**Comment by alexgarces** [comment]
@Gonzalo9823 @daydream05 all packages were updated on v.0.2.0, so it should be just fine. Thanks for reporting! :)
