### ISSUE TITLE
No PostCSS Config found error

### ISSUE THREAD

**Issue by BenjaminWatts** [alexgarces/react-typeform-embed#3]
Any idea how to respond to this bug?

`Error in ./~/react-typeform-embed/lib/ReactTypeformEmbed/ReactTypeformEmbed.css
Module build failed: Error: No PostCSS Config found in: /Users/xxxxxxx/auth0react/node_modules/react-typeform-embed/lib/ReactTypeformEmbed
    at <anonymous>
 @ ./~/react-typeform-embed/lib/ReactTypeformEmbed/ReactTypeformEmbed.css 4:14-153 18:2-22:4 19:20-159`

**Comment by alexgarces** [comment]
@BenjaminWatts do you still have this issue? I didn't manage to reproduce it. :(

**Comment by BenjaminWatts** [comment]
Hi - I gave up!


Yours sincerely,

Ben Watts (CGMA, MA Cantab) 
+44 7730 611821
Founder

**Comment by alexgarces** [comment]
@BenjaminWatts in the last version I removed the CSS module and replaced it with inline CSS, so this issue should be fixed. 

Thanks for the feedback anyway! :)
