### ISSUE TITLE
Wrong information autoClose props

### ISSUE THREAD

**Issue by dachristo** [alexgarces/react-typeform-embed#33]
autoClose | PRO+ accounts only. Time until the embedded typeform should automatically close after a respondent clicks the Submit button. Your typeform will automatically close after the time you specify, so respondents won’t have to manually close your typeform popup. In `seconds`.Popup mode option | N/A
-- | -- | --

**Comment by alexgarces** [comment]
Hello,

On the last version, README has been updated with a link to the official documentation regarding supported options (https://developer.typeform.com/embed/configuration/#available-options), so this info has been removed.

Cheers.
