### ISSUE TITLE
Handle Errors

### ISSUE THREAD

**Issue by JacopoBonta** [alexgarces/react-typeform-embed#37]
There are no error handlers like `onError` or something like this and when an error occurs, like this one:

![Screenshot 2020-06-17 at 12 18 20](https://user-images.githubusercontent.com/9072396/84886387-a64e0200-b094-11ea-8ce5-177f2e2747f2.png)

from my understanding, there is nothing one can do about it.

**Comment by aloukianova-godaddy** [comment]
Also - Seems to be making a request to `admin.typeform.com`, even though that is not the passed-in `surveyUrl`. Why is this making additional requests?

**Comment by criestlav** [comment]
Any update about this?

**Comment by ankesh7** [comment]
Our Sentry is overflowing these errors. Any insights to handle this will be appreciated. Thanks

**Comment by niklaslavrell** [comment]
According to this issue: https://github.com/Typeform/embed/issues/83, this might be solved by upgrading `@typeform/embed` to latest version.

**Comment by elyxer** [comment]
I fixed mine with a little help from https://github.com/Typeform/embed.
had the same error when with this code:

![Screen Shot 2021-03-10 at 3 15 13 PM](https://user-images.githubusercontent.com/28538887/110590948-6ba47080-81b3-11eb-81e9-98326055107c.png)


Fixed it when I switched to using '@typeform/embed' in
![Screen Shot 2021-03-10 at 3 13 42 PM](https://user-images.githubusercontent.com/28538887/110590782-3566f100-81b3-11eb-8b04-949db38d5b1d.png)
