### ISSUE TITLE
Add support for missing embed modes

### ISSUE THREAD

**Issue by juniorclearmetal** [alexgarces/react-typeform-embed#45]
The Embed Modes offered in the app are Standard, Full-page, Popup, Slider, Popover, and Side Tab. This library appears to only support Popup (`popup=true`) and, I assume, Full-page (if `popup=false`). It appears the only way to use the others is to use the copy-and-paste code snippet in the admin.

**Comment by tacosjs** [comment]
Bump this. Don't have time to update the repos myself but will enjoy having the other embed options.

**Comment by alexgarces** [comment]
Hello,

The other embed modes have been added to the last version (`1.0.1`). Take a look to the README and the `src/examples` folder to see how to implement them.

Hope it helps!

Cheers.
