### ISSUE TITLE
onSubmit callback support

### ISSUE THREAD

**Issue by sbounmy** [alexgarces/react-typeform-embed#7]
Hello,

I just saw that ```onSubmit``` callback is missing
It would be great to support it
https://developer.typeform.com/embed/onsubmit-callback/

🍺

**Comment by scrofungulus** [comment]
+1

**Comment by scrofungulus** [comment]
I've opened a pull request for this issue: https://github.com/alexgarces/react-typeform-embed/pull/9

**Comment by S1rFrancis** [comment]
Didn't see the above PR, also created one: https://github.com/alexgarces/react-typeform-embed/pull/10

**Comment by alexgarces** [comment]
@S1rFrancis @byerc thanks for the feedback and the PR's! I'll review them in the next days and try to implement the functionality. It shouldn't be a problem if the official API supports it. :)

**Comment by alexgarces** [comment]
#9 Done!

Thank you both @S1rFrancis and @byerc.
